services:
  brew_web:
    # This is hosted in its own repository
    image: mpse2/brewlogger-web
    hostname: brew_web
    restart: always
    environment:
     - API_KEY=akljnv13bvi2vfo0b0bw789jlljsdf
    networks:
      - brew_net
    ports:
      - 8080:8080
    depends_on:
      - brew_api

  brew_api:
    build: service-api
    hostname: brew_api
    restart: always
    #ports:
    #  - 8000:80
    networks:
      - brew_net
    environment:
     - API_KEY=akljnv13bvi2vfo0b0bw789jlljsdf
     - DATABASE_URL=postgresql://postgres:password@brew_db:5432/app
     - API_KEY_ENABLED=0
     - REDIS_URL=brew_cache
     - BREWFATHER_API_KEY=
     - BREWFATHER_USER_KEY=
    depends_on:
     - brew_db
     - brew_cache

  brew_cache:
    image: redis:7
    hostname: brew_cache
    restart: always
    networks:
      - brew_net

  brew_db:
    image: postgres:14
    hostname: brew_db
    restart: always
    networks:
      - brew_net
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=brew_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

  brew_pgadmin:
    image: dpage/pgadmin4
    hostname: brew_pgadmin
    restart: always
    networks:
      - brew_net
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  brew_mdns:
    build: service-mdns
    hostname: brew_mdns
    container_name: mdns
    restart: always
    network_mode: "host"
    privileged: true
    environment:
      USE_MDNS_REPEATER: 1
      EXTERNAL_INTERFACE: en0
      DOCKER_NETWORK_NAME: brewnet
      OPTIONS: ""
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  brew_ble:
    build: service-ble
    hostname: brew_ble
    networks:
      - brew_net
    restart: always
    privileged: true
    environment:
      MIN_INTERVAL: 300
    volumes:
      - /dev:/dev
      - /var/run/dbus:/var/run/dbus

networks:
  brew_net:

volumes:
  pg-data:
  pgadmin-data:
